name: Dependency Review

on:
  pull_request_target: {}
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          fail-on-severity: low