name: Notify new PR
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  notify_job:
    runs-on: ubuntu-latest
    name: New PR created to repo
    steps:
    - name: Checks out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get codeowners
      run: |
        sudo apt-get update && sudo apt-get install -y jq curl
        curl -o codeowners.tar.gz https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_linux_amd64.tar.gz  | tar xvf codeowners.tar.gz && cp codeowners/codeowners /usr/local/bin/codeowners
        codeowners --help
    - name: Get user's e-mail
      id: user_email
      run: |
        echo "AUTHOR_EMAIL=$(git log -n 1 --pretty=format:%ae)"
    # - name: Send GitHub trigger payload to Slack Workflow Builder
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.26.0
    #   with:
    #     payload: |
    #       {
    #         "url": "${{ github.event.pull_request.html_url }}",
    #         "title": "${{ github.event.pull_request.title }}",
    #         "sender": "${{ steps.user_email.outputs.AUTHOR_EMAIL }}"
    #       }
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
